### ISSUE TITLE
OpenL3 acknowledgement

### ISSUE THREAD

**Issue by justinsalamon** [torchopenl3/torchopenl3#57]
Hey folks,

I love that you've ported OpenL3 to pytorch!

Since torchopenl3 is a direct port of OpenL3, we (OpenL3 team) would greatly appreciate it if openl3 were properly acknowledged in your README file.

Right now the top-level description reads:
```
TorchopenL3 is an open-source Python library Pytorch Support for computing deep audio embeddings.
```

It would be fairer if it read:
```
TorchopenL3 is a pytorch port of the OpenL3 Python library for computing deep audio embeddings.
```
With the word [OpenL3](https://github.com/marl/openl3) linking to the original repo.

Right now OpenL3 is only mentioned after the contributors, and the text suggests it's just a keras version, rather than the original version on which this port is based. That's not quite fair. For the same reason, I think it's fair to ask that if people use torchopenl3, that they cite your provided reference _and_ the openl3 paper (and, ideally, the original L3-net paper as well).

Thanks!

**Comment by turian** [comment]
Thanks! We have pushed a fix to the README. Our pytests are breaking CI/CD, I think because of some Python dependency version changing. We'll try to debug that before pushing to pypi.

**Comment by turian** [comment]
@justinsalamon and please let us know if there are other changes, we want to make sure openl3 gets the credit it deserves. It's amazing work.

**Comment by turian** [comment]
This is now merged and live on pypi.
